In [1]:
import numpy as np

In [6]:
# Basics
a = np.array([1, 4, 5])
a

array([1, 4, 5])

In [8]:
# 2d array
a = np.array([[1, 3, 5], [4, 5, 5]])
print(a)

[[1 3 5]
 [4 5 5]]


In [9]:
# Get dimensions
a.ndim

2

In [10]:
# Get Shape
a.shape

(2, 3)

In [11]:
# Get type
a.dtype

dtype('int64')

ACCESSING / CHANGING ROWS AND COLUMNS ETC...


In [16]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [17]:
# Get specific element
a[1, 5]

13

In [18]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [19]:
# Get specific column
a[:, 2]

array([ 3, 10])

In [21]:
# Get elements with steps [startindex : endindex : stepsize] --> End index is exclusive
a[0, 1:6:2]

array([2, 4, 6])

INITIALIZING DIFFERENT ARRAYS


In [23]:
# All zeros matrix
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
# All 1s matrix
np.ones((2, 4, 3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [25]:
# Any other number
np.full((1, 3), 17)

array([[17, 17, 17]])

In [31]:
# Random decimal values
np.random.rand(4, 5)

array([[0.37920261, 0.2499693 , 0.67503823, 0.84132332, 0.17252442],
       [0.27381448, 0.13338614, 0.37391084, 0.94244406, 0.57256748],
       [0.07923922, 0.3431915 , 0.6592699 , 0.56870418, 0.64899219],
       [0.41826661, 0.1451971 , 0.76805964, 0.26724521, 0.35811944]])

In [34]:
# Random int values
np.random.randint(5, size = (4, 5))

array([[3, 1, 4, 4, 2],
       [0, 1, 3, 3, 3],
       [4, 3, 1, 4, 3],
       [2, 3, 0, 3, 1]])

In [38]:
# Random int values in a range
np.random.randint(-4, 5, size = (4, 5))

array([[ 3, -2, -4, -1, -4],
       [-1,  1,  0,  1,  1],
       [ 2,  0,  1, -1,  2],
       [ 0,  3,  4,  2,  2]])

In [39]:
# Identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [42]:
# Repitition of an array
x = np.array([[1, 3, 5]])
r = np.repeat(x, 3, axis = 0)
print(r)

[[1 3 5]
 [1 3 5]
 [1 3 5]]


In [46]:
r = np.repeat(x, 3, axis = 1)
print(r)

[[1 1 1 3 3 3 5 5 5]]


In [56]:
out = np.ones((5, 5), dtype='int8')
print(out)

z = np.zeros((3, 3), dtype='int8')
z[1, 1] = 9
print(z)

out[1:4, 1:4] = z
print(out)


[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0]
 [0 9 0]
 [0 0 0]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


BE CAREFUL WHEN COPYING ARRAYS


In [60]:
# Never do b = a. It would alter the orginal array as well
a = np.array([1, 3, 5])
b = a.copy()
b

array([1, 3, 5])

In [63]:
# Won't change a
b[1] = 0
print(b)
print(a)

[1 0 5]
[1 3 5]


MATHEMATICAL OPERATIONS
            

In [64]:
a = np.array([1, 3, 5])
a

array([1, 3, 5])

In [65]:
a + 2

array([3, 5, 7])

In [66]:
a - 2

array([-1,  1,  3])

In [67]:
a * 2

array([ 2,  6, 10])

In [68]:
a / 3

array([0.33333333, 1.        , 1.66666667])

In [71]:
b = np.array([2, 4, 1])
a + b

array([3, 7, 6])

In [72]:
# Sin of all the elements
np.sin(a)

array([ 0.84147098,  0.14112001, -0.95892427])

LINEAR ALGEBRA

In [78]:
# Matrix multiplication
a = np.ones((2, 3))
print(a)

b  = np.full((3, 2), 2)
print(b)

print(np.matmul(a, b))
print(np.matmul(b, a))

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]


STATISTICS

In [83]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a


array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
np.min(a)

1

In [87]:
np.min(a, axis=1)

array([1, 4])

In [88]:
np.sum(a)

21

In [89]:
np.sum(a, axis=0)

array([5, 7, 9])

REORGANIZING ARRAYS

In [93]:
# Reshaping
before = np.array([[1, 3, 4, 5], [3, 5, 7, 1]])
print(before)

after = before.reshape((8, 1))
print(after)

[[1 3 4 5]
 [3 5 7 1]]
[[1]
 [3]
 [4]
 [5]
 [3]
 [5]
 [7]
 [1]]


In [95]:
# Vertically stacking
a = np.array([1, 3, 5, 6])
b = np.array([2, 7, 8, 1])
np.vstack([a, b])

array([[1, 3, 5, 6],
       [2, 7, 8, 1]])

OTHER IMPORTANT FEATURES

In [97]:
# Loading data from a file
filedata = np.genfromtxt('data.txt', delimiter = ",")
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


BOOLEAN MASKING AND INDEXING


In [98]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [100]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [103]:
# List of indices
a = np.array([1, 3, 4, 5, 6, 2, 5, 6, 2])
a[[0, 2, 1]]

array([1, 4, 3])